version: "3.8"

networks:
  laravel:

services:
  web:
    build:
      context: .
      dockerfile: web.dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
    depends_on:
      - php
    networks:
      - laravel
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    working_dir: "/var/www/html"
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
  supervisor:
      build:
        context: .
        dockerfile: supervisor.dockerfile
      volumes:
        - .:/var/www/html
  npm:
    image: node:latest
    container_name: npm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ "npm" ]
    networks:
      - laravel
